# Generated by Django 5.1.7 on 2025-03-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book 1'), ('can_create', 'Can create book 2'), ('can_edit', 'Can edit book 3'), ('can_delete', 'Can delete book 4')]},
        ),
    ]
