services:
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: no
    # restart: always
    # restart: unless-stopped
    # restart: on-failure:3  # Retries up to 3 times on failure
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: